public class CandidateTriggerHelper {
    /*List<Job_Rasika__c> job{get; set;}
public static void checkJobStatus(List<Candidate_Rasika__c> candidates)
{
    Map<String,Job_Rasika__c> jobMap=new Map<String ,Job_Rasika__c>([SELECT  id,Name,Active_status__c FROM Job_Rasika__c
                                                                         WHERE Active_status__c!=true ]);
    for(Candidate_Rasika__c candidate: candidates)
    {
        
        
    }        
        
}*/
}