public class helper1 {
    public static void fun1(List<Job_Rasika__c> jdlist){
        for(Job_Rasika__c jd: jdlist){
        	System.debug(Trigger.new);
        }
    }
    public static void fun2(List<Job_Rasika__c> jdlist){
        for(Job_Rasika__c jd: jdlist){
        	System.debug(Trigger.new);
        }
    }
    public static void fun3(List<Job_Rasika__c> jdlist){
        for(Job_Rasika__c jd: jdlist){
        	System.debug(Trigger.old);
        }
    }
    public static void fun4(List<Job_Rasika__c> jdlist){
        for(Job_Rasika__c jd: jdlist){
        	System.debug(Trigger.old);
        }
    }
    public static void fun5(List<Job_Rasika__c> jdlist){
        for(Job_Rasika__c jd: jdlist){
        	System.debug(Trigger.new);
        }
    }
    public static void fun6(List<Job_Rasika__c> jdlist){
        for(Job_Rasika__c jd: jdlist){
        	System.debug(Trigger.new);
        }
    }
    public static void fun7(List<Job_Rasika__c> jdlist){
        for(Job_Rasika__c jd: jdlist){
        	System.debug(Trigger.new);
        }
    }
    public static void fun8(List<Job_Rasika__c> jdlist){
        for(Job_Rasika__c jd: jdlist){
        	System.debug(Trigger.old);
        }
    }
    public static void fun9(List<Job_Rasika__c> jdlist){
        for(Job_Rasika__c jd: jdlist){
        	System.debug(Trigger.old);
        }
    }
}