public class helper2 {
    public static void fun1(List<Candidate_Rasika__c> jdlist){
        for(Candidate_Rasika__c jd: jdlist){
        	System.debug(Trigger.new);
        }
    }
    public static void fun2(List<Candidate_Rasika__c> jdlist){
        for(Candidate_Rasika__c jd: jdlist){
        	System.debug(Trigger.new);
        }
    }
    public static void fun3(List<Candidate_Rasika__c> jdlist){
        for(Candidate_Rasika__c jd: jdlist){
        	System.debug(Trigger.old);
        }
    }
    public static void fun4(List<Candidate_Rasika__c> jdlist){
        for(Candidate_Rasika__c jd: jdlist){
        	System.debug(Trigger.old);
        }
    }
    public static void fun5(List<Candidate_Rasika__c> jdlist){
        for(Candidate_Rasika__c jd: jdlist){
        	System.debug(Trigger.new);
        }
    }
    public static void fun6(List<Candidate_Rasika__c> jdlist){
        for(Candidate_Rasika__c jd: jdlist){
        	System.debug(Trigger.new);
        }
    }
    public static void fun7(List<Candidate_Rasika__c> jdlist){
        for(Candidate_Rasika__c jd: jdlist){
        	System.debug(Trigger.new);
        }
    }
    public static void fun8(List<Candidate_Rasika__c> jdlist){
        for(Candidate_Rasika__c jd: jdlist){
        	System.debug(Trigger.old);
        }
    }
    public static void fun9(List<Candidate_Rasika__c> jdlist){
        for(Candidate_Rasika__c jd: jdlist){
        	System.debug(Trigger.old);
        }
    }
}